apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfp-app
  namespace: bushfire-plan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bfp-app
  template:
    metadata:
      labels:
        app: bfp-app
    spec:
      containers:
      - name: bfp-app
        image: <<docker_user>>/bfp-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_WS_URL
          value: "ws://bushfire-plan-service.bushfire-plan.svc.cluster.local:8000"
        - name: PDF_SERVICE_URL
          value: "http://<<PDF generator service>>/generate-pdf"
        - name: USE_DEV_AUTH
          value: "false"
        - name: KEYCLOAK_ISSUER_URL
          value: "http://<<Keycloak service domain>>/auth/realms/<<your realm>>"
        - name: KEYCLOAK_CLIENT_ID
          value: "<<client id>>"
        - name: REDIS_HOST
          value: "<<Redis service domain>>"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USERNAME
          value: "<<Redis username or 'default'>>"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-pw
        - name: REDIS_TLS
          value: "false"
---
apiVersion: v13
kind: Service
metadata:
  name: bfp-service
  namespace: bushfire-plan
spec:
  selector:
    app: bfp-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
